version: "0.0.5-dev"
description: ESP-Hosted provides driver such that any host can re-use ESP chipset as Wi-Fi or Bluetooth co-processor.
url: https://github.com/espressif/esp-hosted/tree/feature/esp_as_mcu_host
dependencies:
  idf:
    version: ">=5.0"
license: "Apache-2.0"

name: Push component to https://components.espressif.com
on:
  push:
    branches:
      - feature/esp_as_mcu_host
jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@v1
        with:
          name: "esp_hosted"
          version: "0.0.5-dev"
          namespace: "espressif"
          api_token: ${{ IDF_COMPONENT_API_TOKEN }}
